<%@ include file="/JSTLTagLibIncludes.jsp" %>
<!-- 
	This version of the menu is displayed when DDS is deployed stand-alone (outside of dlese.org).
	Original OPML generated by DLESE Headliner 2.2b, modified later and placed in JSP so variables can be used.
	
	Note, pass in to the viewing page param treeCache=off/on to turn on/off caching of the menu view
-->
<c:set var="isForegroundIndex" value="${applicationScope.isForegroundIndex}"/>

<opml version="2.0" xmlns:trees="http://www.dlese.org/Metadata/ui/trees"> 
	<head>
		<title>Digital Discovery System (DDS)</title>
		<!-- The context attribute below is written by the DDSServlet class with the value of the installed context path, e.g. "/dds/" -->
		<trees:menu images="${pageContext.request.contextPath}/images/opml_menu/triangles_bullets/" context="${pageContext.request.contextPath}/"/> 
		<dateModified>Fri, 20 Feb 2009 13:26:32 MDT</dateModified>
	</head>
	<body>
		<outline text="Home" type="link" description="Home: Digital Discovery System (DDS)" url="index.jsp"/>
		<outline text="Search" type="link" description="Search the DDS repository" url="dds_search.jsp"/>
		<outline text="&lt;hr&gt;" type="separator"/>
		<outline text="Manage the Repository" type="link" description="Manage and view collections and items in the repository" url="admin/index.jsp">
			<outline text="Collection Manager" type="link" description="View and manage collections in the repository" url="admin/admin.do"/>
			<c:if test="${!isForegroundIndex}">
				<outline text="Repository Maintenance" type="link" url="admin/maintenance.do" description="Maintain the Repository"/>
			</c:if>
			<outline text="Advanced Search" type="link" description="Search, view and manage items in the repository" url="admin/query.do" />
			<c:if test="${fn:endsWith(param.requestURI,'admin/editing.do')}">
				<outline text="Edit Record" type="link" url="admin/editing.do"/>
			</c:if>
			<c:set var="oaiSettingsUrl">
				<c:choose>
					<c:when test="${fn:endsWith(param.requestURI,'admin/update_repository_info.do')}">admin/update_repository_info.do</c:when>
					<c:when test="${fn:endsWith(param.requestURI,'admin/repository_info-validate.do')}">admin/repository_info-validate.do</c:when>
					<c:otherwise>admin/data-provider-info.do</c:otherwise>
				</c:choose>
			</c:set>
			<outline text="OAI Data Provider Settings" type="link" description="Manage OAI data provider settings" url="${fn:trim(oaiSettingsUrl)}"/>				
			<outline text="&lt;hr&gt;" type="separator"/>			
			<c:if test="${fn:endsWith(param.requestURI,'admin/display.do')}">
				<outline text="Full Record View" type="link" url="admin/display.do"/>
			</c:if>
			<outline text="Indexed Fields &amp; Terms" description="View the search fields and terms in the repository" type="link" url="admin/reporting/index_page.jsp"/>
			<c:if test="${fn:endsWith(param.requestURI,'admin/reporting/report.do')}">
				<outline text="Fields/Terms Viewer" type="link" url="admin/reporting/report.do"/>
			</c:if>
			<outline text="Reports" description="View reports for the repository" type="link" url="admin/reporting/reports.jsp"/>
			<c:if test="${fn:endsWith(param.requestURI,'admin/report.do')}">
				<outline text="Report Viewer" type="link" url="admin/report.do"/>
			</c:if>
		</outline>		
		<outline text="&lt;hr&gt;" type="separator"/>
		<%-- <outline text="Services and APIs Overview" type="link" description="Services and APIs Overview" url="services/index.jsp"/> --%>				
		
		
		
		<outline text="Search API" type="link" description="Information about the Search API" url="services/ddsws1-1/index.jsp">
			<outline text="Documentation" type="link" url="services/ddsws1-1/service_specification.jsp"/>
			<outline text="Search Client" type="link" url="services/examples/ddsws1-1/index.jsp"/>
			<outline text="Explorer" type="link" url="services/ddsws1-1/service_explorer.jsp"/>
		</outline>
		<outline text="Update API" type="link" description="Update, create, and delete collections and items" url="services/ddsupdatews1-1/ddsupdatews_api_documentation.jsp"/>
		
		<outline text="&lt;hr&gt;" type="separator"/>
		<outline text="Repository Analytics" type="link" url="repository_analytics.do" description="View Repository Analytics Stats"/>
		
		<outline text="&lt;hr&gt;" type="separator"/>
		<outline text="OAI Data Provider" description="Explore the OAI Data Provider" url="services/oaiDataProvider/oai_explorer.jsp" type="link"/>
		<outline text="&lt;hr&gt;" type="separator"/>
		<outline text="Download and Configure" type="link" description="Information about installing and configuring DDS" url="docs/index.jsp">
			<outline text="Install or Build" description="Installation Instructions for DDS" url="docs/dds_installation_instructions.jsp" type="link" />
			<outline text="Configure Data Sources" description="Configure data sources for DDS" url="docs/configure_dds_data_sources.jsp" type="link" />
			<outline text="Configure Search" description="Configure the fields, facets, and relationships that are used for search" url="docs/configure_dds_search_fields.jsp" type="link" />
		</outline>
		<outline text="About DDS" type="link" description="Information about DDS" url="docs/about_dds.jsp"/>						
	</body>
</opml>