<%@ include file="/JSTLTagLibIncludes.jsp" %>

<%@ page import="edu.ucar.dls.schemedit.security.access.ActionPath" %>
<c:set var="contextPath"><%@ include file="/ContextPath.jsp" %></c:set>
<c:set var="title" value="Manage Users"></c:set>
<c:set var="sessionUserIsAdmin" value="${sf:hasRole (sessionScope['user'], 'admin')}" />
<html:html locale="true">
<head>
<%@ include file="/manage/access/accessHTMLIncludes.jsp" %>
<script>

// images must be defined so they are accessible to item-table.js
var openedImg = "${contextPath}/images/btnExpand.gif"
var closedImg = "${contextPath}/images/btnExpandClsd.gif"

function pageInit () {
	
	itemTableInit();

	// highlight current user, if appropriate
	var username = "${umForm.username}";
	
	// when a user has just been removed from managedUsers (by removing access to all
	// collections)
	if (username != "" && $(username+"_widget")) {
		toggleVisibility (username);
		highlight ($(username+"_widget"));
		$(username+"_widget").scrollTo()
	}

	// initialize handler for "edit-item-button
	$$(".edit-item-button").each ( function (button) 
		{ editUserButtonInit (button); });
	
	$$(".edit-access-button").each ( function (button) 
		{ editAccessButtonInit (button); });
		
	$$(".delete-user-button").each ( function (button) 
		{ deleteUserButtonInit (button); });
		
}
	
// handles "change" events generated by the "add_user_select" dropdown
function addUserHandler (evnt) {
	var username = $F('add_user_select');
	if (username == "")
			alert ("Please select an existing user");
	else {
		var params = {
			username : username,
			command  : "edit",
			add      : true
			}
		  window.location="${contextPath}/manage/userManager.do?" + $H(params).toQueryString();
	}
}

// initialize a "editAccess" button to respond to the "click" event
function editAccessButtonInit (button) {
		var user = button.id.substr ("edit-access-".length);
		button.observe ('click', function (evnt) { 
			Event.stop (evnt);
			var params = {
				username : user,
				command  : "edit"
			}
			var href = "${contextPath}/manage/userManager.do?" + $H(params).toQueryString();
			// alert (href);
			window.location = href;
		} );
}
					
					
// initialize a "editItem" button to respond to the "click" event
function editUserButtonInit (button) {
		var user = button.id.substr ("edit-item-".length);
		button.observe ('click', function (evnt) { 
			Event.stop (evnt);
			var params = {
				username : user,
				command  : "edit",
				referer  : "${contextPath}/manage/userManager.do?username="+user
			}
			var href = "${contextPath}/user/userInfo.do?" + $H(params).toQueryString();
			// alert (href);
			window.location = href;
		} );
}

// initialize a "delete user" button to respond to the "click" event
function deleteUserButtonInit (button) {
		var user = button.id.substr ("delete-".length);
		button.observe ('click', function (evnt) { 
			Event.stop (evnt);
			var params = {
				username : user,
				command  : "delete"
			}
			var href = "${contextPath}/manage/userManager.do?" + $H(params).toQueryString();
			if (confirm ("Do you really want to delete \"" + user + "\"?\n(This action cannot be undone)")) {
				// alert (href);
				window.location = href;
			}
		} );
}

// handles events generated by the newUser button
function newUserHandler () {
	// Event.stop (evnt);
	var params = {
		command  : "create",
		referer  : "${contextPath}/manage/userManager.do"
	}
	var href = "${contextPath}/user/userInfo.do?" + $H(params).toQueryString();
	// alert (href);
	window.location = href;
}

Event.observe (window, 'load', pageInit);
	
</script>

<title><st:pageTitle title="${title}" /></title>
<%-- <html:base/> --%>
</head>
<body bgcolor="white" style="font-family:arial;font-size:80%">
<st:pageHeader currentTool="manage" toolLabel="${title}" />

<p>Manage the users that have access to the collections you manage. To add users to your
collections, you can create a <span class="doc-em">new user</span>, 
or add an <span class="doc-em">existing user</span>,
and then specify the collections the user can access.
</p>

<st:pageMessages />


<c:if test="${authenticationEnabled}">

	<html:form action="/manage/userManager" >
	
	<div style="margin-top:20px;">
	<table>
		<tr>
			<td align="left">
				<input type="button" value="Create new user" 
						onclick="newUserHandler()" />
				</div>
			</td>
			<c:if test="${not sessionUserIsAdmin && not empty umForm.managableUsers}" >
				<td align="left">
						<select id="add_user_select" onchange="addUserHandler()">
							<option value="">-- add existing user --</option>
							<c:forEach var="user" items="${umForm.managableUsers}">
								<option value="${user.username}">${user.lastName}, ${user.firstName} (${user.username})</option>
							</c:forEach>
						</select>
					</div>
				</td>
			</c:if>
			<td width="50px">&nbsp;</td>
			<td align="left" style="white-space:nowrap">
					<div class="action-link">[ <a href="#" id="open-items-button">open all</a> |
					<a href="#" id="close-items-button">close all</a> ]</div>
			</td>
		</tr>
	</table>
	</div>
	
	<div align="center" style="margin-top:0px;">
		<table class="item-table">
		<tr class="header-row">
			<td align="left" width="300px">
				<span class="table-title">Users:
				&nbsp;&nbsp;</span>
				Lastname, Firstname (Login)
			</td>
			<td colspan="4" align="left">Institution</td>
		</tr>
		<c:forEach var="user" items="${umForm.users}">
			<c:set var="current_user" value="${user.username == umForm.username}" />
			<tr class="item-table-row">
				<td style="white-space:nowrap" align="left" width="300px"><a name="${user.username}"></a>
					<c:set var="displayName"><b>${user.lastName}, ${user.firstName}</b> (${user.username})</c:set>
	
								<html:link styleId="${user.username}_widget"
											href="#"
											styleClass="open-close-widget" 
											title="Click to show/hide">
									<img class="widget-img"
											src='${contextPath}/images/btnExpandClsd.gif' 
											alt="Click to show/hide" />
									<c:choose>
										<c:when test="${user.isAdminUser}" ><i>${displayName}</i></c:when>
										<c:otherwise>${displayName}</c:otherwise>
									</c:choose>
								</html:link>
	
				</td>
				<td>${user.institution}</td>
				<td width="100px" align="center">
					<a href="#" class="edit-item-button" id="edit-item-${user.username}">edit user info</a>
				</td>
				<td width="100px" align="center"><c:if test="${not user.isAdminUser}" >
						<a href="#" class="edit-access-button" id="edit-access-${user.username}">edit access</a> 
						</c:if>
				</td>
				<c:set var="canDelete" value="${not user.isAdminUser || (sessionUserIsAdmin && user.username != 'root')}" />
				<td width="100px" align="center"><c:if test="${canDelete}" >
						<a href="#" class="delete-user-button" id="delete-${user.username}">delete user</a> 
						</c:if>
				</td>
			</tr>
				<tr id="${user.username}_id" style="display:none">
					<td colspan="5" class="no-border">
							<table class="inner-table">
							<c:choose>
								<c:when test="${user.isAdminUser}" >
									<tr>
										<td>
											<div class="indented"><i>Administrators have access to all collections</i></div>
										</td>
									</tr>
								</c:when>
								<c:otherwise>
									<c:set var="hasCollection" value="${false}" />
									<c:forEach var="crBean" items="${umForm.userRoleMap[user.username]}">
										<c:if test="${not empty crBean.role && crBean.role != 'none'}">
											<tr>
													<c:set var="hasCollection" value="${true}" />
													<td style="white-space:nowrap">
														<div class="indented">
															<a title="See all users having access to this collection"
																href="${contextPath}/manage/collectionAccessManager.do?collection=${crBean.collectionKey}"
																class="manage-link">${crBean.collectionName}</a>
														</div>
													</td>
													<td align="center">
														<%-- ${crBean.collectionKey} --%>
													</td>
													<td width="300px" align="center">
														<div class="${crBean.role}-role">${crBean.role}</div>
													</td>
											</tr>
										</c:if>
									</c:forEach>
									<c:if test="${not hasCollection}">
										<tr>
											<td>
												<div class="indented"><i>This user has access to no collections.</i></div>
											</td>
										</tr>
									</c:if>
								</c:otherwise>
								</c:choose>
							</table>
						<%-- </div> --%>
					</td>
				</tr>
		</c:forEach>
	</table>
	
	</div>
	</html:form>
</c:if>

</body>
</html:html>
