/*
Instantiated in AffiliationTool.jsp

Handles events generated by affiliationTool.jsp, most notably:
- done - which calls setData before closing
- cancel - which calls clearData before closing

Sets up search fields and writes their values to helper.toolData,
from where it is writen to the instance record (upon save).

"helper" is an instance of affiliationHelper (affiliationHelper.js) which is
instantiated by the affiliationWidget (affiliationWidget.jsp).

"searcher" is an instance of PeopleSearcher (people-search.js) and is instantiated in 
AffiliationTool.jsp.

*/
var AffiliationTool = Class.create ( {
	initialize: function (helper, searcher) {
		this.helper = helper;
		this.searcher = searcher;
		this.doneButton = $('done-button');
		this.doneButton.observe ('click', function () {
			this.setData();
			this.close();
		}.bind(this));
		this.doneButton.disable();
		this.cancelButton = $('cancel-button');
		this.cancelButton.observe ('click', function () {
			this.clearData();
			this.close();
		}.bind(this));
		// initialize the values in the searcher from metadata record
		this.record_data = this.helper.getRecordData();
		this.initSearcherFields ()
	},

	initSearcherFields: function () {
		$('ucasLastName').value = this.record_data['lastName'];
		// $('ucasMiddleName').value = this.record_data['middleName'];
		$('ucasFirstName').value = this.record_data['firstName'];
		$('upid').value = this.record_data['upid'];
	},

	close: function () {
		top.Windows.getFocusedWindow().close();
	},

	/* debugging: get data from the instance record */
	showRecordData: function(data) {
		var debugEl = $('debug');
		if (!debugEl) return;
		debugEl.update();
		$H(record_data).each(function (pair) {
			debugEl.insert ('<div>'+pair.key+': '+pair.value+'</div>');
		});
	},

	/* clear the data read by affiliationHelper.js */
	clearData: function() {
		log ('clear data');
		helper.toolData = null;
	},

	/* set data in helper.toolData from selected result in the searcher
		upon "done" the helper.toolData is written to the instance record
	*/
	setData: function () {
		log ('AffiliationTool.setData()!!')
		var selectedPerson = this.searcher.selectedPerson;
		
		var normalizeName = function (name) {
			if (name && name.length == 2 && name.indexOf('.') == 1)
				return name.substr(0,1);
			return name;
		}
		
		if (selectedPerson) {
			helper.toolData = {};
			helper.toolData['firstName'] = normalizeName(selectedPerson.firstName);
			helper.toolData['middleName'] = normalizeName(selectedPerson.middleName);
			helper.toolData['lastName'] = selectedPerson.lastName;
			helper.toolData['upid'] = selectedPerson.upid;
			helper.toolData['instDivision'] = selectedPerson.instDivision;
			helper.toolData['isExternal'] = selectedPerson.isExternal;
			if (selectedPerson.isExternal) {
				helper.toolData['instName'] = selectedPerson.externalOrg;
				log ("toolData.instName set to: " + selectedPerson.instName);
			}
		}
		else {
			log (" selectedPerson not found");
		}

	}
});
